Utilities add-in
UrbanInstitute/dataviz-components pull request #10
Opened 2024-01-08 19:57 UTC by benkates

Added two helper functions, kebabCase() and dollarFormat(), along with tests.

2024-01-08 21:12 UTC, mitchthorson requested changes
This looks great, a couple of small comments left inline. One other thing would be great to include here is adding a line about what's been added to `CHANGELOG.md` file. The way I generally do this, is any features to be included in the next release, I create a new section at the top, and instead of a version number just label it as "Next" like so:
```
## Next

- Add `dollarFormat` utility function
- Add `kebabCase` utility function
```

and then once it is time to release the new version, I just go an update the 'Next' label to match the new version number.

2024-01-08 21:12 UTC, mitchthorson commented on src/lib/utils/dollarFormat.js
> +export default function dollar_format(x) {
Maybe stick with camelCase for function names for consistency? `dollarFormat` instead of `dollar_format`

2024-01-08 21:12 UTC, mitchthorson commented on src/index.test.js
>  });
i'm thinking we organize vitetest tests like these to be close to the modules they relate to, so maybe move these tests to a new test file like `src/lib/utils/index.test.js`. This way we can keep all the relevant stories and tests co-located with the components and modules they relate to.

2024-01-09 17:53 UTC, benkates commented
@mitchthorson changes incorporated for your review! thank you!

2024-01-09 18:01 UTC, mitchthorson approved these changes

2024-01-09 18:01 UTC, mitchthorson commented
LGTM!

2024-01-09 18:39 UTC, merged