add layercake components, stories and docs
UrbanInstitute/dataviz-components pull request #111
Opened 2024-08-08 21:46 UTC by rachelmarconi

### What's in this pull request
- [x] New component/feature

### Description

Adding Layercake axes components according to what was used in the medical debt project. 

NOTE: the axis components have since been updated on Layercake, so we can update further or not. Some of the new parameters could be very useful. [New AxisX](https://layercake.graphics/components/AxisX.svelte). [New AxisY](https://layercake.graphics/components/AxisY.svelte).

TODO: 
- [ ] add code chunks for css if updating manually

### Before submitting, please check that you've

- [ ] Formatted your code correctly (i.e., prettier cleaned it up)
- [x] Documented any new components or features
- [x] Added any changes in this PR to the `CHANGELOG.md` `Next` section
- [x] If this pull request includes a new component or feature, has it been exported from one of the library's entry points?
- [x] Does the component dispatch relevant interaction events? (ie: on:click, on:change, etc.)
- [x] Does the component directory include description and usage information in `.stories.svelte`?

2024-08-21 15:49 UTC, mitchthorson requested changes
This is looking really good! I left a few organizational comments and a few nitty-gritty technical comments. Let me know if you want to talk through any of the details here!

2024-08-21 15:49 UTC, mitchthorson commented on src/lib/Layercake/AxisX.docs.md
> +```
Consider moving the import examples up under the "Usage" subhead and above the CSS example. I think this part is one of the first things the user/reader should see if they're quickly scanning the docs for how to import/use a specific component - a more likely and frequent task than using the CSS override for the users of the library.

2024-08-21 15:49 UTC, mitchthorson commented on src/lib/Layercake/AxisX.docs.md
> +
I think this is really important context for using these (and any future) Layercake components, but since it applies to the whole category, I'm wondering if we should move this bit of documentation out of each component doc and into a separate markdown or mdx file. I'd name this document something like "Layercake/Intro" (see screenshot).
<img width="290" alt="Screenshot 2024-08-20 at 4 47 18 PM" src="https://github.com/user-attachments/assets/e5d7e8ed-6002-4af1-a2cc-bd239e20607d">


This way we can move the component-specific usage info closer to the top here, and we don't have to repeat this for each and every Layercake component.

I also think it would be great to add a line to this description that links to the full Layercake documentation website. Maybe just add something at the end like:
"Read more about using Layercake [here](https://layercake.graphics/)"

2024-08-21 15:49 UTC, mitchthorson commented on src/lib/Layercake/AxisY.docs.md
> +Layercake axes must be built inside a Layercake component and context, and, further, within an Svg component. Both can be imported from the layercake package. The Layercake object must be passed flat
This can be removed once the separate overview doc page exists

2024-08-21 15:49 UTC, mitchthorson commented on src/lib/Layercake/AxisY.docs.md
> +```
Move this import example up under "Usage" subhead, above CSS example

2024-08-21 15:49 UTC, mitchthorson commented on src/lib/Layercake/AxisX.svelte
> +  /** @type {Boolean} [gridlines=true] - Extend lines from the ticks into the chart space */
So this is a bit annoying, but Storybook has some differing opinions on how these JSDoc type annotations should be formatted than Layercake does, so I'd suggest a couple of changes:
- The type itself ("Boolean" in this case) should be lowercase like: `@type {boolean}`
- The description should actually come before the type declaration, on a separate line within the comment. If it is done this way, that description actually shows up within the storybook control table.

So for this example, it would end up looking like this:
```
  /** 
   * Extend lines from the ticks into the chart space
   * @type {boolean} [gridlines=true]
   */
  export let gridlines = false;
```

Once formatted like this, you can see how the description renders:
<img width="1034" alt="Screenshot 2024-08-20 at 5 03 49 PM" src="https://github.com/user-attachments/assets/f933e6f8-a715-42e9-b5e2-a253fc5f2ac7">

2024-08-21 15:49 UTC, mitchthorson commented on src/lib/Layercake/AxisX.stories.svelte
> +      },
Once the type annotations are updated to use the lowercase names (see comment below about this), these default control decorations aren't necessary anymore. Storybook will default to the "boolean" control for "boolean" type props.

2024-08-21 15:49 UTC, mitchthorson commented on src/lib/Layercake/AxisX.stories.svelte
> +      },
More default controls that can be removed when type annotations are updated to lowercase.

2024-08-21 15:49 UTC, mitchthorson commented on src/lib/Layercake/AxisX.svelte
> +  export let axisLabel = null;
Update these type annotations as well

2024-08-21 15:49 UTC, mitchthorson commented on src/lib/Layercake/AxisY.stories.svelte
> +      },
More defaults that can be removed after type annotations are updated.

2024-08-21 15:49 UTC, mitchthorson commented on src/lib/Layercake/AxisY.stories.svelte
> +      },
More config that can be removed once type annotations are updated. Any description stuff here should be in the type annotation so it shows up everywhere. Also I think it might be slighly misleading to state that `dx` and `dy` are equal to `xTick` and `yTick`. They're similar and can be used to acheive the same effect, but they can also be used differently and are mapped to seperate SVG properties. See this for more context: https://stackoverflow.com/questions/19127035/what-is-the-difference-between-svgs-x-and-dx-attribute

2024-08-21 15:49 UTC, mitchthorson commented on src/lib/Layercake/AxisY.svelte
> +  export let axisLabel = null;
Update these type signatures just like the ones in AxisX.

2024-08-28 16:46 UTC, rachelmarconi commented on src/lib/Layercake/AxisX.svelte
> +  /** @type {Boolean} [gridlines=true] - Extend lines from the ticks into the chart space */
looks like it expects "text" rather than "string", so I kept the declarations for `axisLabel`s, but the other changes cleaned it up quite a bit!

2024-08-28 17:00 UTC, mitchthorson commented on .storybook/preview.js
> +          "Layercake",
Ok just one tiny last suggestion: to have the "Intro" page listed at the top of the Layercake section, just add one additional line below "Layercake" here:
```
...
"Layercake",
 ["Intro"],
...
```

Which should result in this ordering:

<img width="373" alt="Screenshot 2024-08-28 at 12 59 39 PM" src="https://github.com/user-attachments/assets/4b50d16f-578c-422c-aa94-ff2ddde02341">

2024-08-28 17:34 UTC, mitchthorson approved these changes

2024-08-28 19:54 UTC, merged