Fix: Handle threshold scale ticks more effectively
UrbanInstitute/dataviz-components pull request #113
Opened 2024-09-05 18:31 UTC by mitchthorson

### What's in this pull request

- [x] Bug fix

### Description

Improves the handling of threshold scale ticks.

### Before submitting, please check that you've

- [ ] Formatted your code correctly (i.e., prettier cleaned it up)
- [ ] Documented any new components or features
- [ ] Added any changes in this PR to the `CHANGELOG.md` `Next` section
- [ ] If this pull request includes a new component or feature, has it been exported from one of the library's entry points?
- [ ] Does the component dispatch relevant interaction events? (ie: on:click, on:change, etc.)
- [ ] Does the component directory include description and usage information in `.stories.svelte`?

2024-09-06 14:42 UTC, benkates requested changes
Looking good! Just needs jsdoc for 2 props

2024-09-06 14:42 UTC, benkates commented on src/lib/maps/ColorLegend/ColorLegend.svelte
> +  export let naSpacing = 16;
Jsdoc here

2024-09-06 20:33 UTC, mitchthorson commented on src/lib/maps/ColorLegend/ColorLegend.svelte
> +  export let naSpacing = 16;
Good catch, these are added!

2024-09-09 13:35 UTC, rachelmarconi commented on src/lib/maps/ColorLegend/ColorLegend.svelte
> +  $: console.log(legendTicks);
found a console log

2024-09-09 13:36 UTC, mitchthorson commented on src/lib/maps/ColorLegend/ColorLegend.svelte
> +  $: console.log(legendTicks);
good catch!

2024-09-09 15:12 UTC, benkates approved these changes

2024-09-09 15:13 UTC, merged