Datawrapper iframe component w/ event interaction
UrbanInstitute/dataviz-components pull request #18
Opened 2024-01-10 16:53 UTC by benkates

Adds a Datawrapper Iframe component that bring in Datawrapper's [event interaction library](https://developer.datawrapper.de/docs/listening-to-chart-interaction-events) specifically for map datawrapper visualizations.

2024-01-10 20:12 UTC, mitchthorson requested changes

2024-01-10 20:12 UTC, mitchthorson commented on src/lib/DatawrapperIframe/DatawrapperIframe.svelte
> +  });
let's wrap this in a conditional check for window:
```js
if (typeof window !== "undefined") {}
```
so it doesn't bomb during ssr

2024-01-10 20:12 UTC, mitchthorson commented on src/lib/DatawrapperIframe/events.js
> +if (typeof window.datawrapper === "undefined") window.datawrapper = {};
wrap in `window` check

2024-01-10 20:12 UTC, mitchthorson commented on src/lib/DatawrapperIframe/events.js
> +window.addEventListener("message", receiveMessage, false);
wrap in `window` check

2024-01-10 20:12 UTC, mitchthorson commented on src/lib/DatawrapperIframe/datawrapper-event-list.json
smart!

2024-01-12 17:05 UTC, benkates commented
@mitchthorson added window checks! Should be good to go!

2024-01-12 17:06 UTC, mitchthorson approved these changes
LGTM!

2024-01-12 17:06 UTC, merged